ALTER TABLE events
  ADD COLUMN IF NOT EXISTS title_fr VARCHAR(255) NULL AFTER title,
  ADD COLUMN IF NOT EXISTS title_en VARCHAR(255) NULL AFTER title_fr,
  ADD COLUMN IF NOT EXISTS description_fr LONGTEXT NULL AFTER description,
  ADD COLUMN IF NOT EXISTS description_en LONGTEXT NULL AFTER description_fr,
  ADD COLUMN IF NOT EXISTS venue_fr VARCHAR(255) NULL AFTER venue,
  ADD COLUMN IF NOT EXISTS venue_en VARCHAR(255) NULL AFTER venue_fr;
